### PR TITLE
Added 2Fort map to the CTF maps.

### PR DESCRIPTION
**Pull request by ghost**
Adds 2Fort to the repository.

2Fort was created by 100best & is for the CTF gamemode.

- [x] Was this map shared by the author's permission?
- [x] Does the author allow the map to be licensed under GPL-3?

Proof of all this?
https://github.com/100best/100best-piqueserver-maps
See license of repository.

### CODE REVIEW

**Comment by rndtrash** [comment]
Since this map has a roof above the spawn, we need SpadesX to support 3D "spawn box" first (right now it is defined as a set of 2D coordinates).

**Comment by ghost** [comment]
Link to the original txt file for the config for reference when support is added: https://github.com/100best/100best-piqueserver-maps/blob/master/2fort_ctf.txt

**Comment by Haxk20** [comment]
Did the original author allow the map to be PRed here ? Also please use and fill out the PR template (you) put in place :)

**Comment by ghost** [comment]
@Haxk20 I updated the PR text & also fixed the pull request template. Once @rndtrash confirms the Z axis to be correct I'll squash my commits correctly.

**Comment by nonperforming** [comment]
Isn't this Valve's property?

https://wiki.teamfortress.com/wiki/2Fort
https://wiki.teamfortress.com/wiki/2Fort5

**Comment by rndtrash** [comment]
Well, it is inspired by TF2 indeed, but I guess the voxels weren't placed by the Valve employees so it should be good to go. The only thing that really prevents us from merging it is lack of 3D spawn points support in SpadesX.

**Comment by ghost** [comment]
Fixed merge conflict for the future, commits will need to be squashed before merging however.

**Pull request closed without merging**
